# Inhalt der Präsentation (Folien + Sprechertext). Wird von build_pptx.py in PowerPoint und von de/video/ in Videos umgesetzt.
# Typen: titel, bild (Bild links, Text rechts), text (Text, optional Karten), shot (Screenshot groß), stufen (Tabelle), warn.
# bild: Datei in bilder/ (Illustration) oder handbuch/bilder/annot|web (Screenshot) – Auflösung in build_pptx.py.
SLIDES = [
 dict(typ='titel', titel='NOMAD', untertitel='Wissen, das ohne Internet funktioniert',
      zeile='Die deutsche Fassung von Project NOMAD · Stand Oktober 2026 · Version 1.35.2', bild='titel',
      notiz='Willkommen. In dieser Vorstellung geht es um NOMAD: einen kleinen Wissensserver für zu Hause, der auch dann noch funktioniert, wenn das Internet nicht mehr da ist. Wir zeigen, was das ist, wie man es einrichtet und wo seine Grenzen liegen.'),
 dict(typ='bild', titel='Ein Tag ohne Strom', bild='stromausfall',
      punkte=['Plötzlich ist **alles dunkel**', 'Kein Licht, kein WLAN, kein Fernseher', 'Nach einer Stunde wird es still', 'Dann fällt auf: **das Wissen fehlt**'],
      notiz='Stellen Sie sich einen Tag ohne Strom vor. Plötzlich ist es dunkel. Kein Licht, kein WLAN, kein Fernseher. Nach einer Stunde wird es still im Haus. Und dann fällt auf, was eigentlich fehlt: das Wissen.'),
 dict(typ='bild', titel='Was dann nicht mehr geht', bild='kein-internet',
      punkte=['Kein Internet, kein WLAN', 'Kein Streaming, kein Radio über das Netz', 'Das Handy ist schnell leer', 'Nachrichten, Wetter, Karten: nicht erreichbar'],
      notiz='Ohne Strom fällt auch das Internet aus. Kein Streaming, kein Radio über das Netz, und das Handy ist schnell leer. Nachrichten, Wetter und Karten sind nicht mehr erreichbar.'),
 dict(typ='bild', titel='Vor allem fehlt: das Nachschlagen', bild='nachschlagen',
      punkte=['Wikipedia ist **nicht erreichbar**', 'Keine Anleitung für Heizung und Herd', 'Keine Hinweise zur Ersten Hilfe', 'Keine Karte für die Umleitung'],
      notiz='Am meisten fehlt das Nachschlagen. Wikipedia ist nicht erreichbar. Es gibt keine Anleitung für Heizung und Herd, keine Hinweise zur Ersten Hilfe, keine Karte für die Umleitung.'),
 dict(typ='bild', titel='Und die Kinder und Enkel?', bild='kinder',
      punkte=['Filme und Spiele fallen weg', 'Lernen und Üben geht nicht mehr', 'Bücher und Brettspiele helfen', 'Wissen zum Anfassen, auch ohne Bildschirm'],
      notiz='Und die Kinder und Enkel? Filme und Spiele fallen weg, auch das Lernen und Üben. Bücher und Brettspiele helfen. Aber nicht jeder hat die richtigen Bücher im Regal.'),
 dict(typ='bild', titel='Die Idee: Wissen ins Haus holen', bild='idee',
      punkte=['NOMAD holt das Wissen **zu Ihnen**', 'Es läuft auf einem Rechner bei Ihnen', 'Einmal einrichten, einmal laden', 'Danach ganz **ohne Internet**'],
      notiz='Die Idee von NOMAD ist einfach: Das Wissen kommt ins Haus. NOMAD läuft auf einem Rechner bei Ihnen. Sie richten es einmal ein und laden einmal die Inhalte herunter. Danach brauchen Sie kein Internet mehr.'),
 dict(typ='text', titel='Drei Wörter, einfach erklärt',
      karten=[('Ein Server', ['Ein Computer, der anderen etwas gibt', 'Er steht bei Ihnen im Regal']),
              ('Offline', ['Ohne Internet, ohne Netz', 'Alles ist schon im Haus']),
              ('Der Browser', ['Das Fenster, in dem Sie schauen', 'NOMAD öffnen Sie wie eine Internetseite'])],
      notiz='Drei Wörter, einfach erklärt. Ein Server ist ein Computer, der anderen etwas gibt, und er steht bei Ihnen im Regal. Offline heißt: ohne Internet, alles ist schon im Haus. Und der Browser ist das Fenster, in dem Sie schauen; NOMAD öffnen Sie wie eine Internetseite.'),
 dict(typ='shot', titel='So sieht NOMAD aus: die Kommandozentrale', bild='dashboard-de', unter='Die Startseite: Karten, Schnellstart, Supply Depot, Docs, Einstellungen',
      notiz='So sieht NOMAD aus. Das ist die Kommandozentrale, die Startseite. Hier finden Sie Karten, den Schnellstart zum Einrichten, das Supply Depot für weitere Programme, Anleitungen und die Einstellungen. Alles ist auf Deutsch.'),
 dict(typ='bild', titel='Was drinsteckt', bild='bibliothek',
      punkte=['**Wikipedia** (deutsch und englisch) und Nachschlagewerke', '**Karten**: ganze Länder, auch Deutschland', 'Lernen und Üben', 'Ein **Chat mit lokaler KI**', 'Ihre **eigenen Dokumente**'],
      notiz='Was steckt in NOMAD? Die deutsche und die englische Wikipedia und viele Nachschlagewerke, zum Beispiel zu Medizin, Kochen und Reparieren. Karten, bei denen Sie ganze Länder wählen können, auch Deutschland. Lernmaterial. Ein Chat mit einer KI, die auf Ihrem Rechner läuft. Und Ihre eigenen Dokumente.'),
 dict(typ='bild', titel='Weg 1: Die USB-SSD (empfohlen)', bild='usb',
      punkte=['Kleine, schnelle Festplatte am Kabel (ab 512 GB)', 'Fertiges System darauf schreiben', 'Vorhandenen Windows-PC davon starten', '**Windows bleibt unberührt**'],
      notiz='Der einfachste Weg ist eine USB-SSD. Das ist eine kleine, schnelle Festplatte am Kabel mit mindestens 512 Gigabyte. Darauf schreiben Sie ein fertiges System. Dann starten Sie Ihren vorhandenen Windows-Rechner von dieser Platte. Windows selbst bleibt unberührt, es wird nichts gelöscht.'),
 dict(typ='text', titel='Weg 2: Ein eigener Rechner',
      punkte=['Einen Rechner ganz für NOMAD freimachen, zum Beispiel ein altes Notebook', 'Ubuntu installieren, ein kostenloses Betriebssystem', 'Ein Befehl, dann richtet sich NOMAD ein', 'Etwas für Technik-Fans, oder mit Hilfe'],
      notiz='Der zweite Weg ist ein eigener Rechner, zum Beispiel ein altes Notebook. Darauf installieren Sie das kostenlose Betriebssystem Ubuntu und geben einen einzigen Befehl ein. Das ist etwas für Technikfreunde, oder man lässt sich helfen.'),
 dict(typ='shot', titel='Schnellstart in vier Schritten', bild='35-schnellstart-1', unter='Apps · Karten · Inhalte · Überprüfen',
      notiz='Eingerichtet wird mit dem Schnellstart in vier Schritten: Apps, Karten, Inhalte und Überprüfen. Sie haken an, was Sie möchten, und NOMAD lädt es herunter.'),
 dict(typ='shot', titel='Inhalte: drei Stufen', bild='39-medizin-stufen', unter='Deutsch: Basis ≈ 0,5 GB · Standard ≈ 6,7 GB · Umfassend ≈ 23 GB  (Englisch: 6 · 36 · 89 GB)',
      notiz='Jeder Themenbereich hat drei Stufen: Basis, Standard und Umfassend. Basis ist das Wichtigste und klein. Alle deutschen Bereiche zusammen sind in der Basisstufe nur etwa ein halbes Gigabyte, in Standard etwa 6,7 und in Umfassend etwa 23 Gigabyte. Die englischen Bereiche sind größer, bis zu 89 Gigabyte. Die deutsche Wikipedia kommt je nach Wunsch dazu, von 0,14 bis 51 Gigabyte.'),
 dict(typ='shot', titel='Karten: ganze Länder wählen', bild='map02-laender-waehlen', unter='Deutschland bis Stadtebene: etwa 0,12 GB, mit einzelnen Straßen: etwa 5,6 GB',
      notiz='Bei den Karten wählen Sie ein Land und den Detailgrad. Deutschland bis zur Stadtebene braucht nur etwa 120 Megabyte. Mit jeder einzelnen Straße sind es etwa 5,6 Gigabyte. NOMAD zeigt die Größe vorher an.'),
 dict(typ='stufen', titel='Ab wann geht es ohne Internet?',
      kopf=['Stufe', 'Das geht ohne Internet', 'Das braucht Internet'],
      zeilen=[['A. Gestartet', 'Rechner starten, Anleitungen lesen', 'Alles Weitere'],
              ['B. Inhalte geladen', 'Wikipedia und Nachschlagewerke lesen und suchen', 'Neue Inhalte, Updates'],
              ['C. Karten geladen', 'Karte der geladenen Länder', 'Weitere Länder'],
              ['D. KI eingerichtet', 'Fragen an den lokalen Assistenten', 'Modell einmal laden']],
      notiz='Ab wann geht es ohne Internet? Direkt nach dem Start können Sie die Anleitungen lesen. Sobald die Inhalte geladen sind, können Sie Wikipedia und die Nachschlagewerke nutzen. Karten und KI brauchen jeweils einmal Internet, damit sie geladen werden. Merksatz: Was Sie herunterladen, braucht Internet. Was Sie lesen oder suchen, nicht.'),
 dict(typ='shot', titel='Der Offline-Test', bild='44-offline-test-terminal', unter='Kabel ziehen · neu starten · Checkliste abhaken',
      notiz='Ob es wirklich funktioniert, zeigt der Offline-Test. Netzwerkkabel ziehen, den Rechner ohne Netz neu starten und die Checkliste im Handbuch abhaken. Machen Sie ihn einmal gründlich, solange das Internet noch erreichbar ist.'),
 dict(typ='bild', titel='Strom: Wie lange läuft das?', bild='energie',
      punkte=['Notebook im Betrieb: etwa **20 Watt**', 'Powerbank 99 Wh: etwa 4 Stunden', 'Powerstation 500 Wh: etwa 21 Stunden', 'Solarpanel 100 W: im Sommer ≈ 350 Wh am Tag, im Winter oft nur 50 bis 100 Wh'],
      notiz='Wie lange läuft das System? Ein Notebook braucht im Betrieb etwa 20 Watt. Eine Powerbank mit 99 Wattstunden reicht für etwa vier Stunden, eine Powerstation mit 500 Wattstunden für etwa einundzwanzig Stunden bei Dauerbetrieb. Ein Solarpanel mit 100 Watt liefert im Sommer rund 350 Wattstunden am Tag, im Winter oft nur 50 bis 100. Im Handbuch steht die Rechnung zum Selbstausfüllen.'),
 dict(typ='bild', titel='Das Handbuch zum Ausdrucken', bild='handbuch',
      punkte=['Rund **55 Seiten**, jeder Schritt mit Bild', 'Eine **Notfall-Karte** für den Küchenschrank', 'Tabellen zum Ausfüllen: Version, Inhalte, Zugangsdaten', 'Als **PDF** und als **Webseite (HTML)**'],
      notiz='Zu NOMAD gehört ein Handbuch zum Ausdrucken. Es hat rund 55 Seiten, jeder Schritt mit Bild. Es gibt eine Notfall-Karte für den Küchenschrank und Tabellen zum Ausfüllen, etwa für den Softwarestand, die geladenen Inhalte und die Zugangsdaten. Es gibt das Handbuch als PDF und als Webseite.'),
 dict(typ='bild', titel='Die Notfall-KI', bild='ki',
      punkte=['Läuft **auf Ihrem Rechner**, ohne Internet', 'Antwortet auf Fragen in ganzen Sätzen', 'Kann Ihre Dokumente und geladene Nachschlagewerke heranziehen', 'Braucht Platz, Arbeitsspeicher und Geduld'],
      notiz='Die Notfall-KI ist ein Sprachassistent, der auf Ihrem Rechner läuft, ohne Internet. Sie stellen Fragen in ganzen Sätzen. Die KI kann Ihre eigenen Dokumente und geladene Nachschlagewerke heranziehen, wenn Sie diese dafür vorbereiten. Sie braucht aber Platz, Arbeitsspeicher und etwas Geduld.'),
 dict(typ='stufen', titel='Wie schnell? Zahlen aus unserem Test',
      kopf=['Messung', 'Nur Prozessor', 'Mit Grafikkarte'],
      zeilen=[['Antwort (Modell gemma4:e4b)', '14 Token/s', '106 Token/s'],
              ['Kontext lesen', '50 Token/s', '2700 Token/s'],
              ['Handbuch „CDC“ (178 MB) durchsuchbar machen', 'ca. 3 Stunden*', '7,5 Minuten'],
              ['Empfehlung', 'ab 16 GB Arbeitsspeicher', 'NVIDIA-Karte ab 8 GB']],
      fuss='* alter Rechner, 4 Kerne, 8 GB; moderner Rechner etwa 3-mal schneller',
      notiz='Wie schnell ist das? Mit einem aktuellen Modell, gemma 4, schafft ein moderner Rechner ohne Grafikkarte etwa 14 Wörterstücke pro Sekunde. Mit einer Grafikkarte sind es 106. Ein Nachschlagewerk durchsuchbar zu machen dauert auf einem alten Rechner Stunden, mit Grafikkarte siebeneinhalb Minuten. Wir empfehlen mindestens 16 Gigabyte Arbeitsspeicher.'),
 dict(typ='warn', titel='Vorsicht: Die KI kann irren', bild='fragen',
      punkte=['Kleine Modelle erfinden Antworten, **auch mit Quellenangabe**', 'Ein 1,7-Milliarden-Modell riet in unserem Test zu gefährlichem Unsinn bei Erster Hilfe', 'Bei Medizin, Sicherheit, Recht: **immer an der Quelle prüfen**', 'Die KI ist ein Helfer zum Suchen, **kein Arzt**'],
      notiz='Eine wichtige Warnung: Die KI kann irren. In unserem Test hat ein kleines Modell eine Frage zu Plattenplatz mit einer erfundenen Geschichte über ein Funkgerät beantwortet, und dazu eine Quelle genannt. Ein sehr kleines Modell riet bei Erster Hilfe zu gefährlichem Unsinn. Prüfen Sie bei Medizin, Sicherheit und Recht jede Antwort an der Quelle. Die KI ist ein Helfer, kein Arzt.'),
 dict(typ='text', titel='Der Stand heute',
      punkte=['Version **1.35.2** veröffentlicht', 'Oberfläche und Anleitungen: **deutsch**', 'USB-System gebaut und in der Testumgebung geprüft, auch das Update', 'Handbuch und Notfall-Karte fertig, PDF und HTML', 'Noch offen: Start an einem **echten Windows-PC**'],
      notiz='Der Stand heute: Version 1.35.2 ist veröffentlicht. Oberfläche und Anleitungen sind deutsch. Das USB-System ist gebaut und in einer Testumgebung geprüft, einschließlich Update. Handbuch und Notfall-Karte sind fertig. Noch offen ist der Start an einem echten Windows-Rechner.'),
 dict(typ='text', titel='Ehrlich gesagt: Grenzen',
      punkte=['Überleben, Vorsorge und medizinische Nachschlagewerke: bisher nur **englisch**', 'Die Kartenbeschriftung ist englisch', 'Kein Mac, keine ARM-Rechner', 'Das Anfangspasswort der USB-SSD ist für alle gleich: bitte ändern', 'Nicht alle Nachschlagewerke kann die KI durchsuchen (PDF-Bücher)'],
      notiz='Zur Ehrlichkeit gehören die Grenzen. Für Überleben, Vorsorge und die medizinischen Nachschlagewerke gibt es bisher nur englische Bücher. Die Beschriftung der Karten ist englisch. Es gibt keine Unterstützung für Mac und ARM-Rechner. Das Anfangspasswort der USB-SSD ist für alle gleich, bitte ändern Sie es. Und bestimmte Nachschlagewerke, die als PDF vorliegen, kann die KI nicht durchsuchen.'),
 dict(typ='text', titel='Häufige Fragen',
      punkte=['**„Muss ich etwas an meinem Windows ändern?“** Nein.', '**„Ist das überhaupt erlaubt?“** Ja, frei nutzbar nach Apache-2.0.', '**„Brauche ich einen neuen Rechner?“** Weg 1 nutzt Ihren vorhandenen PC.', '**„Und wenn das Netz lange wegbleibt?“** Dann bleibt alles nutzbar, solange Strom da ist.'],
      notiz='Häufige Fragen. Muss ich an Windows etwas ändern? Nein. Ist das erlaubt? Ja, die Software ist frei nutzbar. Brauche ich einen neuen Rechner? Beim ersten Weg nicht, er nutzt Ihren vorhandenen PC. Und wenn das Netz lange wegbleibt? Dann bleibt alles nutzbar, solange Strom da ist.'),
 dict(typ='bild', titel='Zum Schluss', bild='schluss',
      punkte=['Sie brauchen: **Strom, einen PC und einmal ein Netz**', 'Alles andere bleibt bei Ihnen im Haus', 'Quellcode: github.com/huppiflupp/project-nomad-de', 'Original: github.com/Crosstalk-Solutions/project-nomad', '**Vielen Dank für Ihre Aufmerksamkeit**'],
      notiz='Zum Schluss: Sie brauchen Strom, einen PC und einmal ein Netz. Alles andere bleibt bei Ihnen im Haus. Den Quellcode und das Handbuch finden Sie im Projekt auf GitHub. Vielen Dank für Ihre Aufmerksamkeit.'),
]
